### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tooconfident** [mclairerrb/prj-rev-bwfs-tea-cozy#5]
Grade: Needs Improvement

Good job with this project.  I liked most of your choices and you show a solid beginning knowledge of flex and other complex css properties like z-index (un-comment it next time 👍 ). You will see my line issue's are more commentary on alternative solutions to your style choices.  I hope you find them nice options to clean things up and make it DRY(Don't Repeat Yourself). Start looking into media queries for responsive design websites. You are totally ready for making your website mobile friendly and getting a head start on that will help you going forward. Great work, a couple changes and you will have it solid.

https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by mclairerrb** [comment]
Thank you for your feedback.  I will try your suggestions and save them for future reference.
